server:
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增
  configuration:
    map-underscore-to-camel-case: false  # 开启驼峰功能
    auto-mapping-behavior: full # 自动映射任何复杂的结果
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml


weixin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wx6ce504ada2e4b17c     #   换成你自己的
  secret: 81a0ef3d7843b1bd8d283288d86c9dfd #换成你自己的

#微信支付配置
# appid
# mch_id 商户号
# key 商户的key【API密匙】
# url api请求地址
# notify_url 服务器异步通知页面路径
weixinpayconfig:
  appid: wx6ce504ada2e4b17c
  #  appid: wx632c8f211f8122c6
  #  appid: wxf503a70f5f45cbd2
  #  mch_id: 1497984412
  mch_id: 1500625891
  #  key: sbNCm1JnevqI36LrEaxFwcaT0hkGxFnC
  key: jrBXpyMVPNY0FCFI42EBShLom7KMaRBa
  url: https://api.mch.weixin.qq.com/pay/unifiedorder
  notify_url: http://mih2wq.natappfree.cc/weixinpay/notifyUrl
